# Package Definitions for Prebuilt IPK Packages

# qbittorrent
Package: qbittorrent
Version: 4.3.5
Architecture: all
Maintainer: Aries2050 <your.email@example.com>
Depends: qt5, libtorrent-rasterbar
Description: A lightweight and efficient BitTorrent client.
