#!/bin/sh
# setup_custom_boot — 自动化 custom-boot.d 管理工具
#
# ⚠️ 重要：任务仅在刷机/升级后首次启动时执行一次（UCI defaults 机制），
#        日常重启不会重复执行。需要每次开机都执行的任务请使用 /etc/init.d/。
#
# 用法:
#   交互式:        ./setup_custom_boot.sh
#   直接创建任务:  ./setup_custom_boot.sh <命令> [参数...]
#
# 命令:
#   init                          初始化 custom-boot.d 目录 + .boot-enabled
#   copy  <源文件> <目标路径>     创建复制文件任务
#   chmod <模式> <目标路径>       创建权限设置任务
#   link  <源文件> <链接路径>     创建符号链接任务
#   exec  <命令>                  创建执行任意命令任务
#   run   <脚本路径>              创建执行外部脚本任务
#   list                          列出所有已注册任务
#   remove <前缀>                 删除指定任务
#
# 示例:
#   ./setup_custom_boot.sh init
#   ./setup_custom_boot.sh copy /etc/dnsmasq.user /etc/dnsmasq.conf
#   ./setup_custom_boot.sh chmod 755 /usr/bin/myapp
#   ./setup_custom_boot.sh link /mnt/sda1/www /www/custom
#   ./setup_custom_boot.sh exec "uci set system.@system[0].hostname=myrouter; uci commit"
#   ./setup_custom_boot.sh list

set -e

BOOT_DIR="/etc/custom-boot.d"
TRIGGER="$BOOT_DIR/.boot-enabled"

# ─── 工具函数 ───

# 获取下一个可用编号
_next_num() {
    local max=0 n
    for d in "$BOOT_DIR"/*/; do
        [ -d "$d" ] || continue
        n=$(basename "$d" | grep -o '^[0-9]*' || echo 0)
        [ "$n" -gt "$max" ] 2>/dev/null && max=$n
    done
    printf "%02d" $((max + 1))
}

# 创建 apply.sh
_make_apply() {
    local num="$1" title="$2" content="$3"
    local task_dir="$BOOT_DIR/${num}-${title}"
    mkdir -p "$task_dir"
    cat > "$task_dir/apply.sh" << 'APPLYHEAD'
#!/bin/sh
# auto-generated by setup_custom_boot
APPLYHEAD
    echo "$content" >> "$task_dir/apply.sh"
    chmod +x "$task_dir/apply.sh"
    echo "  ✅ 已创建: $task_dir/apply.sh"
}

# 安全触发器
_ensure_trigger() {
    if [ ! -f "$TRIGGER" ]; then
        echo "提示: $TRIGGER 不存在，将自动创建"
        touch "$TRIGGER"
    fi
}

_ensure_dir() {
    mkdir -p "$BOOT_DIR"
    _ensure_trigger
}

# ─── 命令实现 ───

cmd_init() {
    echo "=== 初始化 custom-boot.d ==="
    mkdir -p "$BOOT_DIR"
    if [ ! -f "$TRIGGER" ]; then
        touch "$TRIGGER"
        echo "  ✅ 已创建触发文件: $TRIGGER"
    else
        echo "  ℹ️  触发文件已存在"
    fi
    echo "  ✅ 目录已就绪: $BOOT_DIR"
    echo
    echo "现在可以用以下命令添加任务："
    echo "  $0 copy <源> <目标>"
    echo "  $0 chmod <权限> <目标>"
    echo "  $0 exec  <命令>"
}

cmd_copy() {
    local src="$1" dst="$2"
    [ -z "$src" ] && { echo "用法: $0 copy <源文件> <目标路径>"; return 1; }
    [ -z "$dst" ] && { echo "用法: $0 copy <源文件> <目标路径>"; return 1; }
    _ensure_dir
    local num title
    num=$(_next_num)
    title="copy-$(basename "$dst" | tr -c 'a-zA-Z0-9-' '_')"
    _make_apply "$num" "$title" "
# 复制 $src → $dst
if [ -f \"$src\" ]; then
    mkdir -p \"\$(dirname \"$dst\")\"
    cp -f \"$src\" \"$dst\"
    echo \"custom-boot: copied $src → $dst\"
else
    echo \"custom-boot: source not found: $src\" >&2
fi"
}

cmd_chmod() {
    local mode="$1" target="$2"
    [ -z "$mode" ] && { echo "用法: $0 chmod <模式> <目标路径>"; return 1; }
    [ -z "$target" ] && { echo "用法: $0 chmod <模式> <目标路径>"; return 1; }
    _ensure_dir
    local num
    num=$(_next_num)
    _make_apply "$num" "chmod" "
# 设置权限 $mode → $target
if [ -e \"$target\" ]; then
    chmod $mode \"$target\"
    echo \"custom-boot: chmod $mode $target\"
else
    echo \"custom-boot: target not found: $target\" >&2
fi"
}

cmd_link() {
    local src="$1" dst="$2"
    [ -z "$src" ] && { echo "用法: $0 link <源文件> <链接路径>"; return 1; }
    [ -z "$dst" ] && { echo "用法: $0 link <源文件> <链接路径>"; return 1; }
    _ensure_dir
    local num
    num=$(_next_num)
    _make_apply "$num" "link" "
# 符号链接 $src → $dst
if [ -e \"$src\" ]; then
    ln -sf \"$src\" \"$dst\"
    echo \"custom-boot: linked $src → $dst\"
else
    echo \"custom-boot: source not found: $src\" >&2
fi"
}

cmd_exec() {
    local cmd="$1"
    [ -z "$cmd" ] && { echo "用法: $0 exec <命令>"; return 1; }
    _ensure_dir
    local num
    num=$(_next_num)
    _make_apply "$num" "exec" "$cmd"
}

cmd_run() {
    local script="$1"
    [ -z "$script" ] && { echo "用法: $0 run <脚本路径>"; return 1; }
    [ ! -f "$script" ] && { echo "错误: 脚本不存在: $script"; return 1; }
    _ensure_dir
    local num title
    num=$(_next_num)
    title="run-$(basename "$script" .sh | tr -c 'a-zA-Z0-9-' '_')"
    local task_dir="$BOOT_DIR/${num}-${title}"
    mkdir -p "$task_dir"
    cp "$script" "$task_dir/apply.sh"
    chmod +x "$task_dir/apply.sh"
    # 添加 shebang（如果原脚本没有）
    if ! head -1 "$task_dir/apply.sh" | grep -q '^#!'; then
        sed -i '1i#!/bin/sh' "$task_dir/apply.sh"
    fi
    echo "  ✅ 已创建: $task_dir/apply.sh（来自 $script）"
}

cmd_list() {
    echo "=== custom-boot.d 任务列表 ==="
    if [ ! -d "$BOOT_DIR" ]; then
        echo "  (目录不存在)"
        return
    fi
    if [ ! -f "$TRIGGER" ]; then
        echo "  ⚠️  触发文件 .boot-enabled 缺失——任务不会执行！"
    else
        echo "  ✅ 触发文件已就绪"
    fi
    echo
    local count=0
    for d in "$BOOT_DIR"/*/; do
        [ -d "$d" ] || continue
        count=$((count + 1))
        local name apply
        name=$(basename "$d")
        apply="$d/apply.sh"
        if [ -x "$apply" ]; then
            echo "  [$name] ✅ $(head -2 "$apply" | tail -1 | sed 's/^# *//')"
        else
            echo "  [$name] ⚠️  apply.sh 缺失或不可执行"
        fi
    done
    if [ "$count" -eq 0 ]; then
        echo "  (无任务)"
    else
        echo
        echo "  共 $count 个任务"
    fi
}

cmd_remove() {
    local prefix="$1"
    [ -z "$prefix" ] && { echo "用法: $0 remove <前缀编号>  例如: $0 remove 01"; return 1; }
    local found=0
    for d in "$BOOT_DIR"/"$prefix"-*/; do
        [ -d "$d" ] || continue
        echo "  删除: $(basename "$d")"
        rm -rf "$d"
        found=1
    done
    if [ "$found" -eq 0 ]; then
        echo "  未找到前缀为 $prefix 的任务"
    fi
}

cmd_interactive() {
    echo "=== custom-boot.d 交互式配置 ==="
    echo
    echo "可用操作:"
    echo "  1) 复制文件到指定位置"
    echo "  2) 设置文件权限"
    echo "  3) 创建符号链接"
    echo "  4) 执行自定义命令"
    echo "  5) 导入已有脚本"
    echo "  6) 列出所有任务"
    echo "  7) 删除任务"
    echo "  0) 退出"
    echo
    while true; do
        printf "选择操作 [0-7]: "
        read -r choice
        case "$choice" in
            1) printf "源文件路径: "; read -r src; printf "目标路径: "; read -r dst; cmd_copy "$src" "$dst" ;;
            2) printf "权限模式 (如 755): "; read -r mode; printf "目标路径: "; read -r target; cmd_chmod "$mode" "$target" ;;
            3) printf "源文件: "; read -r src; printf "链接路径: "; read -r dst; cmd_link "$src" "$dst" ;;
            4) printf "命令: "; read -r cmd; cmd_exec "$cmd" ;;
            5) printf "脚本路径: "; read -r script; cmd_run "$script" ;;
            6) cmd_list ;;
            7) printf "任务编号前缀: "; read -r prefix; cmd_remove "$prefix" ;;
            0) echo "退出"; exit 0 ;;
            *) echo "无效选项" ;;
        esac
        echo
    done
}

# ─── 入口 ───

case "${1:-}" in
    init)    shift; cmd_init "$@" ;;
    copy)    shift; cmd_copy "$@" ;;
    chmod)   shift; cmd_chmod "$@" ;;
    link)    shift; cmd_link "$@" ;;
    exec)    shift; cmd_exec "$@" ;;
    run)     shift; cmd_run "$@" ;;
    list)    cmd_list ;;
    remove)  shift; cmd_remove "$@" ;;
    ""|-i|--interactive) cmd_interactive ;;
    -h|--help|help)
        echo "用法: $0 [命令] [参数...]"
        echo
        echo "命令:"
        echo "  init              初始化 custom-boot.d 目录 + .boot-enabled"
        echo "  copy  <源> <目标>  创建文件复制任务"
        echo "  chmod <权限> <目标> 创建权限设置任务"
        echo "  link  <源> <目标>  创建符号链接任务"
        echo "  exec  <命令>       创建执行命令任务"
        echo "  run   <脚本>       导入已有脚本为任务"
        echo "  list              列出所有任务"
        echo "  remove <前缀>      删除指定任务"
        echo "  (无参数)           交互式配置"
        ;;
    *)
        echo "未知命令: $1"
        echo "运行 $0 --help 查看帮助"
        exit 1
        ;;
esac
